#!/usr/bin/env node
// Parse the АОП register workbooks (data/*.xlsx) into SQL INSERTs for the
// raw_aop_contracts staging table (see packages/db/migrations/0001_raw_aop.sql),
// then optionally bulk-load them into the local D1 with `wrangler d1 execute`.
//
//   node scripts/load-aop.mjs            # parse → write data/aop-load.sql
//   node scripts/load-aop.mjs --apply    # also: migrate + import into local D1
//
// We parse here in Node (not in a Worker): the construction sheet is ~100 MB of
// XML, well past a Worker's 128 MB memory cap. SheetJS resolves shared strings;
// dates arrive as Excel serials (raw:true) and we convert them to ISO ourselves
// so output is deterministic regardless of the container timezone.

import { execFileSync } from 'node:child_process';
import { createWriteStream, readFileSync } from 'node:fs';
import { once } from 'node:events';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as XLSX from 'xlsx';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const apiDir = resolve(root, 'apps/api');
const outFile = resolve(root, 'data/aop-load.sql'); // data/ is gitignored

const SOURCES = [
  { file: resolve(root, 'data/Храни.xlsx'), dataset: 'храни' },
  { file: resolve(root, 'data/Строителство.xlsx'), dataset: 'строителство' },
];

// Staging columns in workbook order (A–W). `kind` drives value coercion.
const COLUMNS = [
  ['tender_internal_id', 'text'], // A
  ['parent_tender_id', 'text'], //   B
  ['lot_number', 'text'], //         C
  ['unp', 'text'], //                D
  ['subject', 'text'], //            E
  ['authority_name', 'text'], //     F
  ['procedure_type', 'text'], //     G
  ['contract_kind', 'text'], //      H
  ['cpv_code', 'text'], //           I  (numeric in sheet — keep as text)
  ['estimated_value_eur', 'real'], //J
  ['eu_funded', 'int'], //           K
  ['published_ojeu', 'int'], //      L
  ['bids_received', 'int'], //       M
  ['submission_deadline', 'datetime'], // N
  ['annex', 'text'], //              O
  ['contract_number', 'text'], //    P
  ['contract_subject', 'text'], //   Q
  ['contract_start_date', 'date'], //R
  ['contract_end_date', 'date'], //  S
  ['signing_value_eur', 'real'], //  T
  ['current_value_eur', 'real'], //  U
  ['contractor_name', 'text'], //    V
  ['contractor_eik', 'text'], //     W  (numeric in sheet — keep as text)
];
const INSERT_COLS = ['dataset', ...COLUMNS.map(([name]) => name)];
// D1 caps a single SQL statement at 100 KB (enforced locally by miniflare too).
// The data is mostly Cyrillic — 2 UTF-8 bytes/char — so we must budget by byte
// length, not JS string length, and leave margin for the INSERT header.
const MAX_BATCH_BYTES = 90_000;
const MAX_BATCH_ROWS = 500;

// Excel serial → JS Date in UTC. 25569 = days from 1899-12-30 to 1970-01-01;
// the 1899-12-30 epoch already absorbs Excel's 1900 leap-year bug.
function serialToDate(serial) {
  return new Date(Math.round((serial - 25569) * 86_400_000));
}

function cleanStr(v) {
  if (v === null || v === undefined) return null;
  const s = String(v).trim();
  return s === '' ? null : s; // the workbook uses a single space as "empty"
}

function toNumber(v) {
  if (v === null || v === undefined || v === '') return null;
  if (typeof v === 'number') return Number.isFinite(v) ? v : null;
  const n = parseFloat(String(v).replace(/\s/g, '').replace(',', '.'));
  return Number.isFinite(n) ? n : null;
}

function coerce(kind, v) {
  switch (kind) {
    case 'real':
      return toNumber(v);
    case 'int': {
      const n = toNumber(v);
      return n === null ? null : Math.round(n);
    }
    case 'datetime': {
      if (typeof v === 'number') return serialToDate(v).toISOString().replace('.000Z', 'Z');
      return cleanStr(v);
    }
    case 'date': {
      if (typeof v === 'number') return serialToDate(v).toISOString().slice(0, 10);
      return cleanStr(v);
    }
    default:
      return cleanStr(v);
  }
}

function sqlLiteral(kind, value) {
  if (value === null) return 'NULL';
  if (kind === 'real' || kind === 'int') return String(value);
  return `'${String(value).replace(/'/g, "''")}'`;
}

async function writeChunk(stream, str) {
  if (!stream.write(str)) await once(stream, 'drain');
}

async function main() {
  const apply = process.argv.includes('--apply');
  const out = createWriteStream(outFile, { encoding: 'utf8' });
  await writeChunk(
    out,
    `-- Generated by scripts/load-aop.mjs — do not edit by hand.\n` +
      `-- Bulk load for raw_aop_contracts (АОП register workbooks).\n` +
      `DELETE FROM raw_aop_contracts;\n`,
  );

  const header = `INSERT INTO raw_aop_contracts (${INSERT_COLS.join(', ')}) VALUES\n`;
  const headerBytes = Buffer.byteLength(header, 'utf8') + 2; // + trailing ";\n"
  let grand = 0;
  let maxStmtBytes = 0; // sanity check: must stay under D1's 100 KB limit
  const perDataset = {};

  for (const { file, dataset } of SOURCES) {
    process.stderr.write(`==> reading ${file}\n`);
    // SheetJS's ESM build has no fs-bound readFile — read the bytes ourselves.
    const wb = XLSX.read(readFileSync(file), { type: 'buffer', dense: true, cellDates: false });
    const ws = wb.Sheets[wb.SheetNames[0]];
    const rows = XLSX.utils.sheet_to_json(ws, {
      header: 1,
      raw: true,
      defval: null,
      blankrows: false,
    });

    let batch = [];
    let stmtBytes = headerBytes;
    let count = 0;

    const flush = async () => {
      if (batch.length === 0) return;
      const stmt = header + batch.join(',\n') + ';\n';
      maxStmtBytes = Math.max(maxStmtBytes, Buffer.byteLength(stmt, 'utf8'));
      await writeChunk(out, stmt);
      batch = [];
      stmtBytes = headerBytes;
    };

    for (let r = 1; r < rows.length; r++) {
      // skip header (row 0)
      const row = rows[r];
      const vals = [sqlLiteral('text', dataset)];
      for (let c = 0; c < COLUMNS.length; c++) {
        const [, kind] = COLUMNS[c];
        vals.push(sqlLiteral(kind, coerce(kind, row[c])));
      }
      const tuple = `(${vals.join(',')})`;
      const tupleBytes = Buffer.byteLength(tuple, 'utf8') + 2; // + ",\n"
      if (
        batch.length > 0 &&
        (batch.length >= MAX_BATCH_ROWS || stmtBytes + tupleBytes > MAX_BATCH_BYTES)
      ) {
        await flush();
      }
      batch.push(tuple);
      stmtBytes += tupleBytes;
      count++;
    }
    await flush();
    perDataset[dataset] = count;
    grand += count;
    process.stderr.write(`    ${dataset}: ${count.toLocaleString('en-US')} rows\n`);
  }

  out.end();
  await once(out, 'finish');
  process.stderr.write(
    `==> wrote ${grand.toLocaleString('en-US')} rows → ${outFile} ` +
      `(largest statement ${maxStmtBytes.toLocaleString('en-US')} bytes)\n`,
  );

  if (!apply) {
    process.stderr.write(
      `\nNext: apply migration + load into local D1:\n` +
        `  (cd apps/api && wrangler d1 migrations apply sigma --local)\n` +
        `  (cd apps/api && wrangler d1 execute sigma --local --file ${outFile})\n` +
        `Or re-run with --apply to do both now.\n`,
    );
    return;
  }

  const run = (args) => {
    process.stderr.write(`==> wrangler ${args.join(' ')}\n`);
    execFileSync('wrangler', args, { stdio: 'inherit', cwd: apiDir });
  };
  run(['d1', 'migrations', 'apply', 'sigma', '--local']);
  run(['d1', 'execute', 'sigma', '--local', '--file', outFile]);
  process.stderr.write(`\n==> done: ${JSON.stringify(perDataset)}\n`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
